# Generated by Django 2.0.3 on 2018-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRTP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
