# Generated by Django 2.0.3 on 2018-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRTP', '0002_auto_20180529_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srtp',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='srtp',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
