# Generated by Django 2.0.3 on 2018-05-31 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRTP', '0004_auto_20180531_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to='SRTP.team'),
        ),
    ]
