# Generated by Django 2.0.3 on 2018-05-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRTP', '0005_auto_20180531_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srtp',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srtp_team', to='SRTP.team'),
        ),
    ]
