# Generated by Django 2.0.3 on 2018-06-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_scheduling', '0005_auto_20180605_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_scheduling.classroom'),
        ),
        migrations.AlterField(
            model_name='time',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_scheduling.lesson'),
        ),
        migrations.AlterField(
            model_name='time',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_scheduling.teacher'),
        ),
    ]
