# Generated by Django 2.0.3 on 2018-06-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_proj', '0002_teacher_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='graduation_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=30)),
                ('Content', models.TextField(max_length=21845, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher_opinion',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='college',
            new_name='Clooege',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='position',
            new_name='Position',
        ),
        migrations.DeleteModel(
            name='teacher_opinion',
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='AssignmentBook',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_book_project', to='graduation_proj.report'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='FinalReport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_report_project', to='graduation_proj.report'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='Judger',
            field=models.ManyToManyField(null=True, related_name='judger_project', to='graduation_proj.teacher'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='JudgerOpinion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judger_opinion_project', to='graduation_proj.opinion'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='MiddleReport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle_report_project', to='graduation_proj.report'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='SelectTopic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_topic_project', to='graduation_proj.report'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='Student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_project', to='graduation_proj.student'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_project', to='graduation_proj.teacher'),
        ),
        migrations.AddField(
            model_name='graduation_project',
            name='TeacherOpinion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_opinion_project', to='graduation_proj.opinion'),
        ),
    ]
