# Generated by Django 2.0.3 on 2018-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_proj', '0003_auto_20180606_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation_project',
            name='Judger',
            field=models.ManyToManyField(related_name='judger_project', to='graduation_proj.teacher'),
        ),
    ]
