# Generated by Django 2.0.3 on 2018-06-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_proj', '0004_auto_20180606_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Clooege',
            new_name='College',
        ),
    ]
