# Generated by Django 2.0.3 on 2018-06-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('detail', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log', models.TextField(max_length=21845)),
            ],
        ),
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('detail', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('inform', models.TextField(max_length=21845)),
                ('middle', models.TextField(max_length=21845)),
                ('result', models.TextField(max_length=21845)),
                ('archievementrecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PM.archievement')),
                ('checkrecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PM.check')),
                ('moneyrecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PM.money')),
            ],
        ),
    ]
