# Generated by Django 2.0.3 on 2018-06-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archievementrecord',
        ),
        migrations.RemoveField(
            model_name='project',
            name='checkrecord',
        ),
        migrations.RemoveField(
            model_name='project',
            name='moneyrecord',
        ),
        migrations.AddField(
            model_name='archievement',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PM.project'),
        ),
        migrations.AddField(
            model_name='check',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PM.project'),
        ),
        migrations.AddField(
            model_name='money',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PM.project'),
        ),
    ]
